apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstproject
  template:
    metadata:
      labels:
        app: firstproject
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: firstproject
        image: ghcr.io/s686/firstproject:latest
        ports:
        - containerPort: 8080
