name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set image name
        id: set-image-name
        run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t firstproject .

      - name: Tag and Push Docker image
        run: |
          docker tag firstproject $IMAGE_NAME
          docker push $IMAGE_NAME
          
      - name: Push Docker image to GitHub Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker tag firstproject ghcr.io/s686/firstproject:latest
          docker push ghcr.io/s686/firstproject:latest

      # Nexus 관련 로그인 및 푸시 단계
      # - name: Log in to Nexus Registry
      #   run: |
      #     echo "${{ secrets.NEXUS_TOKEN }}" | podman login http://172.17.0.3:8081 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
          
      # - name: Tag and Push Docker image to Nexus
      #   run: |
      #     podman tag firstproject 172.17.0.3:8081/firstproject:latest
      #     podman push 172.17.0.3:8081/firstproject:latest

      # Azure와 Kustomize 관련 추가 단계
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Set environment variable for current time
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ github.repository }}
          tags: ${{ env.NOW }}

      - name: Build and Push to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            WHATAP_HOST=${{ secrets.WHATAP_HOST }}
          tags: ${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}

      # Uncomment if you want to run Trivy vulnerability scanner
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: "${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}"
      #     format: "table"
      #     exit-code: "0"
      #     ignore-unfixed: true
      #     vuln-type: "os,library"
      #     severity: "CRITICAL,HIGH"

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Kubernetes resources
        run: |
          pwd
          cd charts/${{ github.event.repository.name }}
          kustomize edit set image ${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}
          cat kustomization.yaml

      - name: Commit manifest files
        run: |
          cd charts/${{ github.event.repository.name }}
          git checkout HEAD
          git config --global user.email "antaeho0117@gmail.com"
          git config --global user.name "ath"
          git commit -am 'update image tag  ${{ env.NOW }} from Github Action'
          git push origin HEAD
