name: Deploy Azure with Gitops-Kustomize by hjkim

on:      
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "main"

env:
  GIT_OPS_NAME: vivaldi-ops
  OPS_DIR: charts/${{ github.event.repository.name }}
  
jobs:
  ecr-build-push-and-deploy:
    name: azr-build-push-and-deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      
    - name: Log in to Nexus Registry
      run: |
        echo "${{ secrets.NEXUS_TOKEN }}" | podman login http://localhost:8081 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Seoul
        
    - name: Set environment variable for current time
      run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ github.repository }}
        tags: ${{ env.NOW }} # ${{ github.event.inputs.name }}
  
    - name: Build and Push to Azure Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./Dockerfile
        platforms: linux/amd64
        build-args: |
          WHATAP_HOST=${{ secrets.WHATAP_HOST }}
        tags: ${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}

    # Uncomment if you want to run Trivy vulnerability scanner
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: "${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}"
    #     format: "table"
    #     exit-code: "0"
    #     ignore-unfixed: true
    #     vuln-type: "os,library"
    #     severity: "CRITICAL,HIGH"
        
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }} # /${{ env.GIT_OPS_NAME }}
        ref: master
        token: ${{ secrets.ACTION_TOKEN }} # ${{ secrets.GITHUB_TOKEN }} 
        path: ${{ env.GIT_OPS_NAME }}
        
    - name: Update Kubernetes resources
      run: |
        pwd
        cd ${{ env.GIT_OPS_NAME }}/${{ env.OPS_DIR }}
        kustomize edit set image ${{ secrets.AZURE_URL }}/${{ steps.meta.outputs.tags }}
        cat kustomization.yaml

    - name: Commit manifest files
      run: |
        cd ${{ env.GIT_OPS_NAME }}/${{ env.OPS_DIR }}
        git checkout HEAD
        git config --global user.email "antaeho0117@gmail.com"
        git config --global user.name "ath"
        git commit -am 'update image tag  ${{ env.NOW }} from Github Action'
        cat kustomization.yaml
        git push origin HEAD
