name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set image name
        id: set-image-name
        run: echo "IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t firstproject .

      - name: Tag and Push Docker image
        run: |
          docker tag firstproject $IMAGE_NAME
          docker push $IMAGE_NAME
          
      - name: Push Docker image to GitHub Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker tag firstproject ghcr.io/s686/firstproject:latest
          docker push ghcr.io/s686/firstproject:latest

      - name: Tag and Push Docker image to Nexus
        run: |
          podman login http://<NEXUS_IP>:8081 -u "${{ secrets.NEXUS_USERNAME }}" --password "${{ secrets.NEXUS_PASSWORD }}"
          
          # 이미지 태그 및 푸시
          podman tag firstproject localhost:8081/firstproject:latest
          podman push localhost:8081/firstproject:latest
